### ISSUE TITLE
Abiltiy to Download Stable Releases

### ISSUE THREAD

**Issue by AwlsomeAlex** [AwlsomeAlex/ReactOS-Trunk-Downloader#8]
This shouldn't just be a TRUNK Downloader, but include downloading the latest Stable as well!

**Comment by Bassa31** [comment]
Hey AwIsomeAlex,
https://download.reactos.org/reactos
This is a server dedicated for relase. So here you can find all relases (0.x.x- 0.4.0)

**Comment by AwlsomeAlex** [comment]
Thanks Bassa31!
